db:
  configurations:
    localDb:
      url: jdbc:postgresql://35.204.167.2/api_db
      username: api_hga_db
      driver: org.postgresql.Driver
      password: GnApi@hga123!
    public:
      url: jdbc:postgresql://35.204.167.2/api_hga_db
      username: api_hga_db
      driver: org.postgresql.Driver
      password: GnApi@hga123!

